version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: order-management-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: order_management
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Kafka service
  kafka:
    image: bitnami/kafka:3.6
    container_name: order-management-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Order Management Service
#  order-management:
#    build: .
#    container_name: order-management-service
#    ports:
#      - "8080:8080"
#      - "8081:8081"
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev
#      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/order_management
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#    depends_on:
#      mongodb:
#        condition: service_healthy
#      kafka:
#        condition: service_healthy
#    volumes:
#      - ./logs:/app/logs

volumes:
  mongodb_data:
  kafka_data: