version: '3.8'

services:
  # Override for development environment
  order-management:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongodb:27017/order_management?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOGGING_LEVEL_COM_PAKLOG_ORDERMANAGEMENT=DEBUG
    volumes:
      - .:/app
      - ./logs:/app/logs
    # Command to run the application with live reload for development
    command: mvn spring-boot:run