# Development environment configuration
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/order_management
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

# Logging configuration for development
logging:
  level:
    com.paklog.ordermanagement: DEBUG
    org.springframework: INFO
    org.mongodb: WARN
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Micrometer tracing configuration for development
management:
  tracing:
    sampling:
      probability: 1.0  # Trace all requests in development
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  server:
    port: 8081
